switchtolayout;
selectall;
delete;

## SIM PARAMS
num_input_wg = 3;
num_output_wg = 3;
wg_width = 0.5e-6;
wg_dist = 1.5e-6;
mode_width = 3*wg_width;
total_input_wg_h = num_input_wg*wg_width + (num_input_wg-1)*wg_dist;
total_output_wg_h = num_output_wg*wg_width + (num_output_wg-1)*wg_dist;

opt_size_x=6e-6;
opt_size_y=6e-6;

size_x=opt_size_x+2e-6;
size_y=opt_size_y+2e-6;

wg_index = 3.47;
bg_index = 1.44;

dx = 20e-9;
dy = 20e-9;
filter_r = 3;

delta = 0.05e-6;


for( i=1:num_input_wg ) {             
  addrect;
  set('name','input wg '+num2str(i));
  set('x max',-opt_size_x/2 + 5e-7);
  set('x min',-size_x);
  set('y',total_input_wg_h/2 - (wg_width/2) - (i-1)*(wg_dist+wg_width));
  set('y span',wg_width);
  set('z',0);
  set('z span',220e-9);
  set('index',wg_index);
}


for( i=1:num_output_wg ) {             
  addrect;
  set('name','output wg '+num2str(i));
  set('x min',opt_size_x/2 - 5e-7);
  set('x max',size_x);
  set('y',total_output_wg_h/2 - (wg_width/2) - (i-1)*(wg_dist+wg_width));
  set('y span',wg_width);
  set('z',0);
  set('z span',220e-9);
  set('index',wg_index);
}

# # modesource
for(i=3:3){
    addmode;
    set('name','forward_source_'+num2str(i-2));
    set('direction','Forward');
    set('injection axis','x-axis');
    set('amplitude',1);
    set('y',total_input_wg_h/2 - (wg_width/2) - (i-1)*(wg_dist+wg_width));
    set('y span',mode_width);
    set('x',-size_x/2+0.2e-6);
    set('center wavelength',1550e-9+(i-1)*10e-9);
    set('wavelength span',0);
    set('mode selection','fundamental TM mode');
}

addfdtd;                             
    set('dimension','2D');
    set('index',bg_index);
    set('mesh accuracy',3);
    set('x min',-size_x/2);
    set('x max',size_x/2);
    set('y min',-size_y/2);
    set('y max',size_y/2);
    set('auto shutoff min',1e-6);
    set('simulation time',5000e-15);
    setnamed("FDTD","min mesh step", delta);
    
addpower;
    set('name','opt_fields');
    set('monitor type','2D Z-normal');
    set('x min',-(opt_size_x/2 + dx*filter_r));
    set('x max',(opt_size_x/2 + dx*filter_r));
    set('y min',-(opt_size_y/2 + dy*filter_r));
    set('y max',(opt_size_y/2 + dy*filter_r));

addmesh;
    set("name","fields_mesh");
    set('x min',-(opt_size_x/2 + dx*filter_r));
    set('x max',(opt_size_x/2 + dx*filter_r));
    set('y min',-(opt_size_y/2 + dy*filter_r));
    set('y max',(opt_size_y/2 + dy*filter_r));
    set("dx", 0.02e-6);
    set("dy", 0.02e-6);
    set("dz", 0.01e-6);

addindex;
    set('name','opt_index');
    set('x min',-(opt_size_x/2 + dx*filter_r));
    set('x max',(opt_size_x/2 + dx*filter_r));
    set('y min',-(opt_size_y/2 + dy*filter_r));
    set('y max',(opt_size_y/2 + dy*filter_r));

addindex;
    set('name','design_index');
    set('x min',-opt_size_x/2);
    set('x max',opt_size_x/2);
    set('y min',-opt_size_y/2);
    set('y max',opt_size_y/2);

for( i=3:3 ) { 
    addpower;
    set('name','fom_'+num2str(i-2));
    set('monitor type','2D X-normal');
    set('x', size_x/2-0.2e-6);
    set('y',total_output_wg_h/2 - (wg_width/2) - (i-1)*(wg_dist+wg_width));
    set('y span',mode_width);
    set('z',0);
    set('z span',220e-9);
    
    addmodeexpansion;
    set('name','fom_exp_'+num2str(i-2));
    set('monitor type','2D X-normal');
    set('x', size_x/2-0.2e-6);
    set('y',total_output_wg_h/2 - (wg_width/2) - (i-1)*(wg_dist+wg_width));
    set('y span',mode_width);
    set('z',0);
    set('z span',220e-9);
    setexpansion('fom_exp_'+num2str(i-2), 'fom_'+num2str(i-2));
    set("mode selection", "fundamental TM mode");
    setnamed('fom_exp_'+num2str(i-2), 'auto update',true);
    setnamed('fom_exp_'+num2str(i-2), 'override global monitor settings', false);
}   

for( i=3:3 ) { 
    addmode;
    set('name','adjoint_source_'+num2str(i-2));
    set('direction','Backward');
    set('injection axis','x-axis');
    set('x',size_x/2-0.2e-6);
    set('y',total_output_wg_h/2 - (wg_width/2) - (i-1)*(wg_dist+wg_width));
    set('y span',mode_width);
    set('center wavelength',1570e-9);
    set('wavelength span',0);
    set('mode selection','fundamental TM mode');
}  

## Optional: Naive design which can be used as initial guess
#addstructuregroup;
#set("name","initial_guess");
#for( i=1:num_output_wg ){
    #addwaveguide;
    #set("name","bend1_"+num2str(i));
    #set("base width",wg_width);
    #set("base height",240e-9);
    #set("base angle",90);
    #poles = [ -opt_size_x/2,total_input_wg_h/2-wg_width/2;
            #0,total_input_wg_h/2-wg_width/2;
            #0,total_output_wg_h/2-wg_width/2-(i-1)*(wg_dist+wg_width);
            #opt_size_x/2,total_output_wg_h/2-wg_width/2-(i-1)*(wg_dist+wg_width)];
    #set("poles",poles);
    #set("index",wg_index);
    #addtogroup("initial_guess");
#}

#for( i=1:num_output_wg){
    #addwaveguide;
    #set("name","bend2_"+num2str(i));
    #set("base width",wg_width);
    #set("base height",240e-9);
    #set("base angle",90);
    #poles = [ -opt_size_x/2,total_input_wg_h/2-3*wg_width/2-wg_dist;
            #0,total_input_wg_h/2-3*wg_width/2-wg_dist;
            #0,total_output_wg_h/2-wg_width/2-(i-1)*(wg_dist+wg_width);
            #opt_size_x/2,total_output_wg_h/2-wg_width/2-(i-1)*(wg_dist+wg_width)];
    #set("poles",poles);
    #set("index",wg_index);
    #addtogroup("initial_guess");
#}

#for( i=1:num_output_wg){
    #addwaveguide;
    #set("name","bend3_"+num2str(i));
    #set("base width",wg_width);
    #set("base height",240e-9);
    #set("base angle",90);
    #poles = [ -opt_size_x/2,total_input_wg_h/2-5*wg_width/2-2*wg_dist;
            #0,total_input_wg_h/2-5*wg_width/2-2*wg_dist;
            #0,total_output_wg_h/2-wg_width/2-(i-1)*(wg_dist+wg_width);
            #opt_size_x/2,total_output_wg_h/2-wg_width/2-(i-1)*(wg_dist+wg_width)];
    #set("poles",poles);
    #set("index",wg_index);
    #addtogroup("initial_guess");
#}

#addwaveguide;
#set("name","bend4_1");
#set("base width",500e-9);
#set("base height",240e-9);
#set("base angle",90);
#poles = [ -opt_size_x/2,-total_input_wg_h/2+wg_width/2;
           #0,-total)input_wg_h/2+wg_width/2;
           #0,-total_output_wg_h/2+wg_width/2;
           #opt_size_x/2,-total_output_wg_h/2+wg_width/2];
#set("poles",poles);
#set("index",wg_index);
#addtogroup("initial_guess");
